version: '3.8'

services:
  oktzy:
    image: shhmon/oktzy:latest
    container_name: oktzy
    ports:
      - "5000:5000"
    env_file:
      - .env

  oktzy-backend:
    image: shhmon/oktzy-backend:latest
    container_name: oktzy-backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - oktzy-database

  oktzy-database:
    image: postgres:16
    container_name: oktzy-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - oktzy_db_volume:/var/lib/postgresql/data
      - /home/ec2-user/Oktzy/oktzy-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  oktzy_db_volume: