name: Oktzy CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: | 
          echo "${{ secrets.EC2_SECRET }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Okyzy Frontend Image
        run: | 
          docker buildx build --platform linux/amd64 -t shhmon/oktzy:latest --push .

      - name: Deploy services / setup .env file / clean up old images
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "
          cd /home/ec2-user/Oktzy &&
          echo 'NODE_ENV=production' > .env &&
          echo 'NEXT_PUBLIC_API_BASE_URL=https://oktzy.com/api' >> .env &&
          echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> .env &&
          echo 'DB_USER=${{ secrets.DB_USER }}' >> .env &&
          echo 'DB_HOST=${{ secrets.DB_HOST }}' >> .env &&
          echo 'DB_NAME=${{ secrets.DB_NAME }}' >> .env &&
          echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env &&
          echo 'DB_PORT=${{ secrets.DB_PORT }}' >> .env &&
          docker-compose down &&
          docker system prune -af &&
          docker-compose pull &&
          docker-compose up -d" 